#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v20
# autospec commit: a19cdc7
#
Name     : c-blosc2
Version  : 2.15.0
Release  : 3
URL      : https://github.com/Blosc/c-blosc2/archive/v2.15.0/c-blosc2-2.15.0.tar.gz
Source0  : https://github.com/Blosc/c-blosc2/archive/v2.15.0/c-blosc2-2.15.0.tar.gz
Summary  : A blocking, shuffling and lossless compression library
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause MIT Zlib
Requires: c-blosc2-lib = %{version}-%{release}
Requires: c-blosc2-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Our-CMAKE_INSTALL_LIBDIR-already-has-prefix-in-it.patch

%description
========
C-Blosc2
========
A fast, compressed and persistent data store library for C
==========================================================

%package dev
Summary: dev components for the c-blosc2 package.
Group: Development
Requires: c-blosc2-lib = %{version}-%{release}
Provides: c-blosc2-devel = %{version}-%{release}
Requires: c-blosc2 = %{version}-%{release}

%description dev
dev components for the c-blosc2 package.


%package lib
Summary: lib components for the c-blosc2 package.
Group: Libraries
Requires: c-blosc2-license = %{version}-%{release}

%description lib
lib components for the c-blosc2 package.


%package license
Summary: license components for the c-blosc2 package.
Group: Default

%description license
license components for the c-blosc2 package.


%prep
%setup -q -n c-blosc2-2.15.0
cd %{_builddir}/c-blosc2-2.15.0
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1729492893
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -D PREFER_EXTERNAL_LZ4=ON \
-D PREFER_EXTERNAL_ZLIB=ON \
-D PREFER_EXTERNAL_ZSTD=ON \
-W no-dev  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1729492893
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/c-blosc2
cp %{_builddir}/c-blosc2-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/c-blosc2/f95d3411831b0a3233ecbba99b85d2f1688773cd || :
cp %{_builddir}/c-blosc2-%{version}/LICENSES/BITSHUFFLE.txt %{buildroot}/usr/share/package-licenses/c-blosc2/d1b152dfd8ac42778f5d4aacfb62b92bf2ab4145 || :
cp %{_builddir}/c-blosc2-%{version}/LICENSES/FASTLZ.txt %{buildroot}/usr/share/package-licenses/c-blosc2/7f9f00bd71460bbd6551c361fe5e95023ab69ebd || :
cp %{_builddir}/c-blosc2-%{version}/LICENSES/LZ4.txt %{buildroot}/usr/share/package-licenses/c-blosc2/63aa9e87fdd44f2c9627db9a6b6d29a95e6ef53d || :
cp %{_builddir}/c-blosc2-%{version}/LICENSES/ZLIB.txt %{buildroot}/usr/share/package-licenses/c-blosc2/1e0b08e7a2124c67c42261ac819e2340a2dd912c || :
cp %{_builddir}/c-blosc2-%{version}/LICENSES/ZSTD.txt %{buildroot}/usr/share/package-licenses/c-blosc2/c4130945ca3d1f8ea4a3e8af36d3c18b2232116c || :
cp %{_builddir}/c-blosc2-%{version}/internal-complibs/zlib-ng-2.0.7/LICENSE.md %{buildroot}/usr/share/package-licenses/c-blosc2/1e0b08e7a2124c67c42261ac819e2340a2dd912c || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/b2nd.h
/usr/include/blosc2.h
/usr/include/blosc2/blosc2-common.h
/usr/include/blosc2/blosc2-export.h
/usr/include/blosc2/blosc2-stdio.h
/usr/include/blosc2/codecs-registry.h
/usr/include/blosc2/filters-registry.h
/usr/include/blosc2/tuners-registry.h
/usr/lib64/cmake/Blosc2/Blosc2Config.cmake
/usr/lib64/cmake/Blosc2/Blosc2ConfigVersion.cmake
/usr/lib64/cmake/Blosc2/Blosc2Targets-relwithdebinfo.cmake
/usr/lib64/cmake/Blosc2/Blosc2Targets.cmake
/usr/lib64/cmake/Blosc2/Modules/FindIPP.cmake
/usr/lib64/cmake/Blosc2/Modules/FindLZ4.cmake
/usr/lib64/cmake/Blosc2/Modules/FindSIMD.cmake
/usr/lib64/cmake/Blosc2/Modules/FindZLIB_NG.cmake
/usr/lib64/cmake/Blosc2/Modules/FindZSTD.cmake
/usr/lib64/cmake/Blosc2/Modules/toolchain-aarch64.cmake
/usr/lib64/cmake/Blosc2/Modules/toolchain-armhf.cmake
/usr/lib64/cmake/Blosc2/Modules/toolchain-armsf.cmake
/usr/lib64/libblosc2.so
/usr/lib64/pkgconfig/blosc2.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libblosc2.so.2.15.0
/usr/lib64/libblosc2.so.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/c-blosc2/1e0b08e7a2124c67c42261ac819e2340a2dd912c
/usr/share/package-licenses/c-blosc2/63aa9e87fdd44f2c9627db9a6b6d29a95e6ef53d
/usr/share/package-licenses/c-blosc2/7f9f00bd71460bbd6551c361fe5e95023ab69ebd
/usr/share/package-licenses/c-blosc2/c4130945ca3d1f8ea4a3e8af36d3c18b2232116c
/usr/share/package-licenses/c-blosc2/d1b152dfd8ac42778f5d4aacfb62b92bf2ab4145
/usr/share/package-licenses/c-blosc2/f95d3411831b0a3233ecbba99b85d2f1688773cd
